services:
  - type: web
    name: apipilot-server
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: apipilot
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
